### ISSUE TITLE
Parse Error running persevere-example-wiki using Node on Cygwin

### ISSUE THREAD

**Issue by scottbradley** [persvr/persevere-example-wiki#12]
I have downloaded v2 of Persevere, as well as the latest version of Nodules. I am trying to run the Persevere-Example-Wiki and cannot get it to work. I am running CYGWIN on Windows 7 and have Node.js version 4.1 installed. I am getting the following error:

Downloading http://github.com/kriszyp/jack/zipball/master
Downloading http://github.com/miksago/node-websocket-server/zipball/v1.4.01
Downloading http://github.com/felixge/node-formidable/zipball/v0.9.8

node.js:116
    throw e; // process.nextTick error, or 'error event on first tick
Error: Parse Error
    at Client.onData [as ondata](http.js:1433:27)
    at Client._onReadable (net.js:654:27)
    at IOWatcher.onReadable [as callback](net.js:156:10)

**Comment by scottbradley** [comment]
Looks like I'm getting Server errors from the URLs in the persevere-example-wiki???

<pre>
Downloading http://github.com/kriszyp/jack/zipball/master
start: 0
end: 2920
</pre>

<!DOCTYPE html>
<html>
  <head>
    <meta charset='utf-8'>
    <title>GitHub - Server Error</title>
    <link href="common.css" rel="stylesheet" type="text/css" />
    <link href="github.css" rel="stylesheet" type="text/css" />
  </head>
  <body>
    <div id="main">
      <div id="header" class="basic">
        <a class="logo boring" href="/">
          <img src="/images/logov3.png" class="default" alt="gitub" />
          <img src="/images/hover.png" class="hover" alt=github" />
        </a>
        <div class="topsearch">
          <ul class="nav logged_out">
            <li><a href="/">Home</a></li>
            <li><a href="/plans">Pricing and Signup!</a></li>
            <li><a href="/training">Training</a></li>
            <li><a href="http://gist.github.com/">Gist</a></li>
            <li><a href="/blog">Blog</a></li>
            <li><a href="/login">Login</a></li>
          </ul>
        </div>
      </div>
    script type="application/javascript">
    // Detect if the browser is IE or not.
    // If it is not IE, we assume that the browser is NS.

<pre>
node.js:116
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
Error: Parse Error
    at Client.onData [as ondata] (http.js:1439:27)
    at Client._onReadable (net.js:654:27)
    at IOWatcher.onReadable [as callback] (net.js:156:10)
</pre>

**Comment by scottbradley** [comment]
Why is this closed? I have no resolution yet.

**Comment by neonstalwart** [comment]
you must have hit close yourself - it's a common mistake
