### ISSUE TITLE
Dependence problems with deployment with nodules

### ISSUE THREAD

**Issue by aegor** [persvr/persevere-example-wiki#4]
As always, problem in nodules.js:310:13 
Need more reliable way to deploy this first and one example of pintura.
May be, npm ?
Any way to add system/user node.js library repositories to nodules?

node /usr/local/lib/node/.npm/.cache/nodules/0.1.0/package/lib/nodules.js
Downloading http://github.com/kriszyp/promised-io/zipball/master
Downloading http://github.com/kriszyp/commonjs-utils/zipball/master
Downloading http://github.com/kriszyp/pintura/zipball/master
Downloading http://github.com/kriszyp/multi-node/zipball/master
Downloading http://github.com/kriszyp/jsgi-node/zipball/master
Downloading http://github.com/kriszyp/transporter/zipball/master
Downloading http://github.com/kriszyp/persevere/zipball/master
Downloading http://github.com/kriszyp/perstore/zipball/master
Downloading http://github.com/kriszyp/jack/zipball/master
Downloading http://github.com/kriszyp/narwhal/zipball/master
Downloading http://github.com/kriskowal/wiky/zipball/master
Downloading http://nodeload.github.com/kriszyp/commonjs-utils/zipball/master
Downloading http://nodeload.github.com/kriszyp/jsgi-node/zipball/master
Downloading http://nodeload.github.com/kriszyp/perstore/zipball/master
Downloading http://nodeload.github.com/kriszyp/pintura/zipball/master
Downloading http://nodeload.github.com/kriszyp/multi-node/zipball/master
Downloading http://nodeload.github.com/kriszyp/narwhal/zipball/master
Downloading http://nodeload.github.com/kriskowal/wiky/zipball/master
Downloading http://nodeload.github.com/kriszyp/transporter/zipball/master
Downloading http://nodeload.github.com/kriszyp/promised-io/zipball/master
Downloading http://download.github.com/kriszyp-commonjs-utils-v0.1.1-26-gfdb5d48.zip
Downloading http://nodeload.github.com/kriszyp/jack/zipball/master
Downloading http://download.github.com/kriskowal-wiky-d3cc62b.zip
Downloading http://download.github.com/kriszyp-multi-node-30657dd.zip
Downloading http://download.github.com/kriszyp-transporter-v0.1.0-19-g43bf368.zip
Downloading http://download.github.com/kriszyp-jsgi-node-v0.1.1-11-g3b3307c.zip
Downloading http://download.github.com/kriszyp-pintura-v0.1.1-280-g31016af.zip
Downloading http://download.github.com/kriszyp-promised-io-9059d10.zip
Downloading http://download.github.com/kriszyp-perstore-v0.1.1-250-g8e603e1.zip
Downloading http://download.github.com/kriszyp-narwhal-0.1-860-g2b46cdc.zip
Downloading http://download.github.com/kriszyp-jack-0.1-242-g8c74922.zip
Downloading http://nodeload.github.com/kriszyp/persevere/zipball/master
Downloading http://download.github.com/kriszyp-persevere-21c8733.zip
Downloading http://github.com/kriszyp/rql/zipball/master
Downloading http://github.com/kriszyp/tunguska/zipball/master
Downloading http://nodeload.github.com/kriszyp/rql/zipball/master
Downloading http://nodeload.github.com/kriszyp/tunguska/zipball/master
Downloading http://download.github.com/kriszyp-rql-e66e36a.zip
Downloading http://download.github.com/kriszyp-tunguska-8787219.zip

/usr/local/lib/node/.npm/.cache/nodules/0.1.0/package/lib/nodules-utils/promise.js:186
          throw error;
          ^
Error: Object #<an Object> has no method 'charAt' failed to load jar:http://github.com/kriszyp/pintura/zipball/master!/lib/jsgi/static.js
    at Object.<anonymous> (/usr/local/lib/node/.npm/.cache/nodules/0.1.0/package/lib/nodules.js:310:13)
    at /usr/local/lib/node/.npm/.cache/nodules/0.1.0/package/lib/nodules.js:212:30
    at Object.<anonymous> (file:///Users/egor/Devel/Github/node.js/apps/kriszyp-persevere-example-wiki-ec75b54/lib/index.js:6:11)
    at /usr/local/lib/node/.npm/.cache/nodules/0.1.0/package/lib/nodules.js:212:30
    at /usr/local/lib/node/.npm/.cache/nodules/0.1.0/package/lib/nodules.js:113:3
    at /usr/local/lib/node/.npm/.cache/nodules/0.1.0/package/lib/nodules.js:322:7
    at Array.forEach (native)
    at decrementWaiting (/usr/local/lib/node/.npm/.cache/nodules/0.1.0/package/lib/nodules.js:321:14)
    at /usr/local/lib/node/.npm/.cache/nodules/0.1.0/pbash-3.2$ 
bash-3.2$ 
bash-3.2$ 
bash-3.2$ 
bash-3.2$ node --version
v0.2.0

**Comment by kriszyp** [comment]
Hmmm, the version on nodules in npm is pretty old. Why don't you download the latest nodules and try again. (another reason why npm is a fail, there is no way to point at trunk, and for dev everything is always out of date).

**Comment by aegor** [comment]
OK! That is works! 
Kriszyp, you need small bootstrap for nodules for install nodules in nodules-style packaging without any foreign package system.

**Comment by kriszyp** [comment]
Hmm, that's a good idea.
