### ISSUE TITLE
Error while installing example

### ISSUE THREAD

**Issue by piscis** [persvr/persevere-example-wiki#5]
Hi there,

I have a issue installing this example when I´m inside of persevere example wiki and trying to run nodules I get the following error:

/persevere-example-wiki# node ../nodules/lib/nodules.js 

node.js:63
    throw e;
    ^
Error: Cannot set property 'Transporter' of undefined in jar:http://github.com/kriszyp/transporter/zipball/v0.2.1!/lib/jsgi/transporter.js
    at Object.<anonymous> (/root/nodules/lib/nodules.js:594:10)
    at /root/nodules/lib/nodules.js:255:23
    at Object.<anonymous> (file:///root/persevere-example-wiki/lib/index.js:26:6)
    at /root/nodules/lib/nodules.js:255:23
    at /root/nodules/lib/nodules.js:147:3
    at Array.<anonymous> (/root/nodules/lib/nodules.js:386:7)
    at EventEmitter._tickCallback (node.js:55:22)
    at node.js:757:9
cpsos:~/persevere-example-wiki# node -v
v0.2.2

**Comment by kriszyp** [comment]
Looks like a nodules upgrade for asynchronous modules is mistreating transporter as an asynchronous module. Just checked in a fix for nodules that should fix this (if you could update nodules and try again).

**Comment by piscis** [comment]
Hi Kris,

I fetched a fresh version of nodules & persevere-wiki via git, now  I have this issue:

apicpsos:~/persevere-example-wiki# node ../nodules/
cli.js        example/      .git/         lib/          package.json  README.md     test/  
apicpsos:~/persevere-example-wiki# node ../nodules/lib/nodules.js 
Downloading http://github.com/kriszyp/promised-io/zipball/v0.2.1
Downloading http://github.com/kriszyp/pintura/zipball/v0.2.1
Downloading http://github.com/kriszyp/commonjs-utils/zipball/v0.2.1
Downloading http://github.com/kriszyp/multi-node/zipball/v0.2.1
Downloading http://github.com/kriszyp/perstore/zipball/v0.2.1
Downloading http://github.com/kriszyp/narwhal/zipball/master
Downloading http://github.com/kriskowal/wiky/zipball/master
Downloading http://github.com/kriszyp/jsgi-node/zipball/v0.2.1
Downloading http://github.com/kriszyp/jack/zipball/master
Downloading http://github.com/kriszyp/transporter/zipball/v0.2.1
Downloading http://github.com/kriszyp/persevere/zipball/master
Downloading http://nodeload.github.com/kriszyp/jsgi-node/zipball/v0.2.1
Downloading http://nodeload.github.com/kriszyp/jack/zipball/master
Downloading http://nodeload.github.com/kriszyp/transporter/zipball/v0.2.1
Downloading http://nodeload.github.com/kriszyp/perstore/zipball/v0.2.1
Downloading http://nodeload.github.com/kriszyp/narwhal/zipball/master
Downloading http://nodeload.github.com/kriszyp/commonjs-utils/zipball/v0.2.1
Downloading http://nodeload.github.com/kriskowal/wiky/zipball/master
Downloading http://nodeload.github.com/kriszyp/pintura/zipball/v0.2.1
Downloading http://nodeload.github.com/kriszyp/promised-io/zipball/v0.2.1
Downloading http://nodeload.github.com/kriszyp/persevere/zipball/master
Downloading http://nodeload.github.com/kriszyp/multi-node/zipball/v0.2.1
Downloading http://nodeload.github.com/kriszyp/jsgi-node/zipball/v0.2.1 attempt #2
Downloading http://nodeload.github.com/kriszyp/jack/zipball/master attempt #2
Downloading http://nodeload.github.com/kriszyp/transporter/zipball/v0.2.1 attempt #2
Downloading http://nodeload.github.com/kriszyp/perstore/zipball/v0.2.1 attempt #2
Downloading http://nodeload.github.com/kriszyp/narwhal/zipball/master attempt #2
Downloading http://nodeload.github.com/kriszyp/commonjs-utils/zipball/v0.2.1 attempt #2
Downloading http://nodeload.github.com/kriskowal/wiky/zipball/master attempt #2
Downloading http://nodeload.github.com/kriszyp/pintura/zipball/v0.2.1 attempt #2
Downloading http://nodeload.github.com/kriszyp/promised-io/zipball/v0.2.1 attempt #2
Downloading http://nodeload.github.com/kriszyp/persevere/zipball/master attempt #2
Downloading http://nodeload.github.com/kriszyp/multi-node/zipball/v0.2.1 attempt #2
Downloading http://nodeload.github.com/kriszyp/jsgi-node/zipball/v0.2.1 attempt #3
Downloading http://nodeload.github.com/kriszyp/jack/zipball/master attempt #3
Downloading http://nodeload.github.com/kriszyp/transporter/zipball/v0.2.1 attempt #3
Downloading http://nodeload.github.com/kriszyp/perstore/zipball/v0.2.1 attempt #3
Downloading http://nodeload.github.com/kriszyp/narwhal/zipball/master attempt #3
Downloading http://nodeload.github.com/kriszyp/commonjs-utils/zipball/v0.2.1 attempt #3
Downloading http://nodeload.github.com/kriskowal/wiky/zipball/master attempt #3
Downloading http://nodeload.github.com/kriszyp/pintura/zipball/v0.2.1 attempt #3
Downloading http://nodeload.github.com/kriszyp/promised-io/zipball/v0.2.1 attempt #3
Downloading http://nodeload.github.com/kriszyp/persevere/zipball/master attempt #3
Downloading http://nodeload.github.com/kriszyp/multi-node/zipball/v0.2.1 attempt #3

node.js:63
    throw e;
    ^
Error: Timeout failed to load jar:http://github.com/kriszyp/promised-io/zipball/v0.2.1!/lib/process.js
    at Object.<anonymous> (/root/nodules/lib/nodules.js:373:12)
    at /root/nodules/lib/nodules.js:255:23
    at Object.<anonymous> (file:///root/persevere-example-wiki/lib/index.js:2:9)
    at /root/nodules/lib/nodules.js:255:23
    at /root/nodules/lib/nodules.js:147:3
    at Array.<anonymous> (/root/nodules/lib/nodules.js:386:7)
    at EventEmitter._tickCallback (node.js:55:22)
    at node.js:757:9

**Comment by kriszyp** [comment]
Looks like github is having problems with the download servers? I can't seem to download anything from github right now either (directly from the web page).

**Comment by piscis** [comment]
hum okay I will try later :)

**Comment by piscis** [comment]
okay I gave it a another run this morning now with a strange behavior when I start nodules hey fetches all dependencies and drops back to node shell. Enclosed is my shell output: 

apicpsos:~/persevere-example-wiki# node ../nodules/lib/nodules.js 
Downloading http://github.com/kriszyp/pintura/zipball/v0.2.1
Downloading http://github.com/kriszyp/promised-io/zipball/v0.2.1
Downloading http://github.com/kriszyp/multi-node/zipball/v0.2.1
Downloading http://github.com/kriszyp/commonjs-utils/zipball/v0.2.1
Downloading http://github.com/kriszyp/perstore/zipball/v0.2.1
Downloading http://github.com/kriszyp/narwhal/zipball/master
Downloading http://github.com/kriskowal/wiky/zipball/master
Downloading http://github.com/kriszyp/jsgi-node/zipball/v0.2.1
Downloading http://github.com/kriszyp/jack/zipball/master
Downloading http://github.com/kriszyp/transporter/zipball/v0.2.1
Downloading http://github.com/kriszyp/persevere/zipball/master
Downloading http://nodeload.github.com/kriszyp/narwhal/zipball/master
Downloading http://nodeload.github.com/kriszyp/multi-node/zipball/v0.2.1
Downloading http://nodeload.github.com/kriszyp/jack/zipball/master
Downloading http://nodeload.github.com/kriszyp/commonjs-utils/zipball/v0.2.1
Downloading http://nodeload.github.com/kriskowal/wiky/zipball/master
Downloading http://nodeload.github.com/kriszyp/jsgi-node/zipball/v0.2.1
Downloading http://nodeload.github.com/kriszyp/perstore/zipball/v0.2.1
Downloading http://nodeload.github.com/kriszyp/transporter/zipball/v0.2.1
Downloading http://nodeload.github.com/kriszyp/persevere/zipball/master
Downloading http://download.github.com/kriszyp-commonjs-utils-v0.2.0-0-gfdb5d48.zip
Downloading http://download.github.com/kriszyp-narwhal-0.1-862-ga1643ec.zip
Downloading http://download.github.com/kriszyp-persevere-21c8733.zip
Downloading http://download.github.com/kriszyp-jsgi-node-v0.2.0-0-g3b3307c.zip
Downloading http://download.github.com/kriszyp-jack-0.1-280-g9ee3721.zip
Downloading http://download.github.com/kriszyp-perstore-v0.2.1-0-g6b0685e.zip
Downloading http://download.github.com/kriszyp-transporter-v0.2.0-0-g43bf368.zip
Downloading http://download.github.com/kriskowal-wiky-d3cc62b.zip
Downloading http://download.github.com/kriszyp-multi-node-v0.2.1-0-g30657dd.zip
Downloading http://github.com/kriszyp/rql/zipball/v0.2.1
Downloading http://github.com/kriszyp/tunguska/zipball/v0.2.1
Downloading http://nodeload.github.com/kriszyp/pintura/zipball/v0.2.1
Downloading http://nodeload.github.com/kriszyp/promised-io/zipball/v0.2.1
Downloading http://nodeload.github.com/kriszyp/tunguska/zipball/v0.2.1
Downloading http://nodeload.github.com/kriszyp/rql/zipball/v0.2.1
Downloading http://download.github.com/kriszyp-promised-io-v0.2.1-0-g044a6cd.zip
Downloading http://download.github.com/kriszyp-pintura-v0.2.1-0-g8622a17.zip
Downloading http://download.github.com/kriszyp-tunguska-v0.2.1-0-g5a2418c.zip
Downloading http://download.github.com/kriszyp-rql-v0.2.1-0-gbd64ec0.zip
Downloading http://github.com/felixge/node-formidable/zipball/v0.9.8
Downloading http://github.com/dmachi/templify/zipball/master
Downloading http://nodeload.github.com/felixge/node-formidable/zipball/v0.9.8
Downloading http://nodeload.github.com/dmachi/templify/zipball/master
Downloading http://download.github.com/felixge-node-formidable-v0.9.8-0-g6ccf2d5.zip
Downloading http://download.github.com/dmachi-templify-35a39b1.zip
node>.exit

node.js:63
    throw e;
    ^

**Comment by piscis** [comment]
sorry it was my misstake ... its running thx for the quick fix :)
